name: Deploy to remote server via SSH

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Sync compose and startup scripts
        uses: burnett01/rsync-deployments@v4
        with:
          switches: -az --delete
          path: |
            docker-compose.yml
            deploy/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          args: "-e 'ssh -o StrictHostKeyChecking=no -i ${SSH_PRIVATE_KEY}'"

      - name: SSH and deploy compose
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            # Pull new image
            docker compose pull ppsnr-server || true
            # Bring down old and start new
            docker compose up -d --remove-orphans --build
